on:
  - workflow_dispatch
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout
      - name: Install Node.js
        uses: actions/setup-node
        with:
          cache: "pnpm"
          node-version: "latest"
      - name: Install pnpm
        uses: pnpm/action-setup
        with:
          run_install: true