on:
  - workflow_dispatch
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
          version: "latest"
      - uses: actions/setup-node@main
        with:
          cache: "pnpm"
          node-version: "latest"
      - run: pnpm install
      - run: pnpm build