on:
  - workflow_dispatch
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
          version: "latest"
      - uses: actions/setup-node@main
        with:
          cache: "pnpm"
          node-version: "latest"
      - run: pnpm install
      - run: pnpm build
      - uses: actions/upload-pages-artifact@main
        with:
          path: dist/
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@main